**SINAN** -
O Sistema de Informação de Agravos de Notificação - Sinan é alimentado, principalmente, pela notificação e investigação de casos de doenças e agravos que constam da lista nacional de doenças de notificação compulsória (Portaria de Consolidação nº 4, de 28 de Setembro de 2017, Anexo), mas é facultado a estados e municípios incluir outros problemas de saúde importantes em sua região, difilobotríase no município de São Paulo. Sua utilização efetiva permite a realização do diagnóstico dinâmico da ocorrência de um evento na população, podendo fornecer subsídios para explicações causais dos agravos de notificação compulsória, além de vir a indicar riscos aos quais as pessoas estão sujeitas, contribuindo assim, para a identificação da realidade epidemiológica de determinada área geográfica.

In [ ]:
pip install pysus # O pySUS é um pacote Python projetado para acessar dados de saúde pública do Sistema Único de Saúde (SUS) do Brasil.

Collecting pysus
  Downloading pysus-0.14.0-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 7.3 MB/s eta 0:00:00
Collecting Unidecode<2.0.0,>=1.3.6 (from pysus)
  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 14.6 MB/s eta 0:00:00
Collecting aioftp<0.22.0,>=0.21.4 (from pysus)
  Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from pysus)
  Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 4.9 MB/s eta 0:00:00
Collecting cffi==1.15.1 (from pysus)
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 10.6 MB/s eta 0:00:00
Collecting dateparser<2.0.0,>=1.1.8 (from pysus)
  Downloading dateparser-1.2.0-py2.py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 23.7 MB/s eta 0:00:00
Collecting dbfread==2.0.7 (from pysus)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Collecting elasticsearch[preprocessing]==7.16.2 (from pysus)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 23.2 MB/s eta 0:00:00
Collecting fastparquet>=2023.10.1 (from pysus)
  Downloading fastparquet-2024.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 24.6 MB/s eta 0:00:00
Collecting humanize<5.0.0,>=4.8.0 (from pysus)
  Downloading humanize-4.9.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 11.2 MB/s eta 0:00:00
Collecting loguru<0.7.0,>=0.6.0 (from pysus)
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.5 MB/s eta 0:00:00
Collecting numpy==1.26.2 (from pysus)
  Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 34.5 MB/s eta 0:00:00
Collecting pandas>=2.1.0 (from pysus)
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 22.5 MB/s eta 0:00:00
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (14.0.2)
Collecting pycparser==2.21 (from pysus)
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 7.6 MB/s eta 0:00:00
Collecting pyreaddbc>=1.1.0 (from pysus)
  Downloading pyreaddbc-1.2.0.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.8.2)
Collecting tqdm==4.64.0 (from pysus)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.11.0)
Collecting urwid<3.0.0,>=2.1.2 (from pysus)
  Downloading urwid-2.6.11-py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.8/296.8 kB 28.0 MB/s eta 0:00:00
Collecting wget<4.0,>=3.2 (from pysus)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Collecting urllib3<2,>=1.21.1 (from elasticsearch[preprocessing]==7.16.2->pysus)
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 14.6 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (2024.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2023.4)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2023.12.25)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.2)
Collecting cramjam>=2.3 (from fastparquet>=2023.10.1->pysus)
  Downloading cramjam-2.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 52.9 MB/s eta 0:00:00
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2023.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (24.0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1.0->pysus) (2024.1)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.13)
Building wheels for collected packages: pyreaddbc, wget
  Building wheel for pyreaddbc (pyproject.toml) ... done
  Created wheel for pyreaddbc: filename=pyreaddbc-1.2.0-cp310-cp310-manylinux_2_35_x86_64.whl size=89737 sha256=402ebf19abafbc686f7f0da5c061210bf555768d7e1ca6b496a398ab374515f4
  Stored in directory: /root/.cache/pip/wheels/44/9c/3c/0b2efbb6180556cf083065c5c0368bb38a26c83dbd5f9a9ba1
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=57b20a0f07bb372240674d1b6e93fbc903f0915cbe52dfe97205e275733cdddf
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built pyreaddbc wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, pycparser, numpy, loguru, humanize, cramjam, bigtree, aioftp, pandas, elasticsearch, dateparser, cffi, pyreaddbc, fastparquet, pysus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.7
    Uninstalling urllib3-2.0.7:
      Successfully uninstalled urllib3-2.0.7
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.2
    Uninstalling tqdm-4.66.2:
      Successfully uninstalled tqdm-4.66.2
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.22
    Uninstalling pycparser-2.22:
      Successfully uninstalled pycparser-2.22
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: humanize
    Found existing installation: humanize 4.7.0
    Uninstalling humanize-4.7.0:
      Successfully uninstalled humanize-4.7.0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
  Attempting uninstall: cffi
    Found existing installation: cffi 1.16.0
    Uninstalling cffi-1.16.0:
      Successfully uninstalled cffi-1.16.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
Successfully installed Unidecode-1.3.8 aioftp-0.21.4 bigtree-0.12.5 cffi-1.15.1 cramjam-2.8.3 dateparser-1.2.0 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.2.0 humanize-4.9.0 loguru-0.6.0 numpy-1.26.2 pandas-2.2.2 pycparser-2.21 pyreaddbc-1.2.0 pysus-0.14.0 tqdm-4.64.0 urllib3-1.26.18 urwid-2.6.11 wget-3.2

In [ ]:
from pysus.online_data import SINAN
from IPython.display import display
import pandas as pd

In [ ]:
SINAN.list_diseases()

{'ACBI': 'Acidente de trabalho com material biológico',
 'ACGR': 'Acidente de trabalho',
 'ANIM': 'Acidente por Animais Peçonhentos',
 'ANTR': 'Atendimento Antirrabico',
 'BOTU': 'Botulismo',
 'CANC': 'Cancêr relacionado ao trabalho',
 'CHAG': 'Doença de Chagas Aguda',
 'CHIK': 'Febre de Chikungunya',
 'COLE': 'Cólera',
 'COQU': 'Coqueluche',
 'DENG': 'Dengue',
 'DERM': 'Dermatoses ocupacionais',
 'DIFT': 'Difteria',
 'ESQU': 'Esquistossomose',
 'EXAN': 'Doença exantemáticas',
 'FMAC': 'Febre Maculosa',
 'FTIF': 'Febre Tifóide',
 'HANS': 'Hanseníase',
 'HANT': 'Hantavirose',
 'HEPA': 'Hepatites Virais',
 'IEXO': 'Intoxicação Exógena',
 'INFL': 'Influenza Pandêmica',
 'LEIV': 'Leishmaniose Visceral',
 'LEPT': 'Leptospirose',
 'LERD': 'LER/Dort',
 'LTAN': 'Leishmaniose Tegumentar Americana',
 'MALA': 'Malária',
 'MENI': 'Meningite',
 'MENT': 'Transtornos mentais relacionados ao trabalho',
 'NTRA': 'Notificação de Tracoma',
 'PAIR': 'Perda auditiva por ruído relacionado ao trabalho',
 'PEST': 'Peste',
 'PFAN': 'Paralisia Flácida Aguda',
 'PNEU': 'Pneumoconioses realacionadas ao trabalho',
 'RAIV': 'Raiva',
 'SDTA': 'Surto Doenças Transmitidas por Alimentos',
 'SIFA': 'Sífilis Adquirida',
 'SIFC': 'Sífilis Congênita',
 'SIFG': 'Sífilis em Gestante',
 'SRC': 'Síndrome da Rubéola Congênia',
 'TETA': 'Tétano Acidental',
 'TETN': 'Tétano Neonatal',
 'TOXC': 'Toxoplasmose Congênita',
 'TOXG': 'Toxoplasmose Gestacional',
 'TRAC': 'Inquérito de Tracoma',
 'TUBE': 'Tuberculose',
 'VARC': 'Varicela',
 'VIOL': 'Violência doméstica, sexual e/ou outras violências',
 'ZIKA': 'Zika Vírus'}

In [ ]:
SINAN.download('VIOL', years= 2022) #puxando dados sobre violencia de 2022

VIOLBR22.parquet: 100%|██████████| 1.46M/1.46M [02:03<00:00, 11.8kB/s]

/root/pysus/VIOLBR22.parquet

In [ ]:
df_violencia = pd.read_parquet ('/root/pysus/VIOLBR22.parquet')

In [ ]:
display(df_violencia.head())

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_UNIDADE,DT_OCOR,SEM_PRI,...,CONS_IDO,DELEG_IDOS,DIR_HUMAN,MPU,DELEG_CRIA,DELEG_MULH,DELEG,INFAN_JUV,DEFEN_PUBL,DT_ENCERRA
0,2,Y09,20221021,202242,2022,35,355710,2081377,20221020,202242,...,2,2,2,2,2,2,1,2,2,
1,2,Y09,20221021,202242,2022,35,354780,2789590,20221017,202242,...,2,2,2,2,2,2,2,2,2,
2,2,Y09,20221021,202242,2022,35,355030,6143121,20221021,202242,...,2,2,2,2,2,2,1,2,2,
3,2,Y09,20221021,202242,2022,35,355030,2029596,20221018,202242,...,2,2,2,2,2,2,2,2,2,
4,2,Y09,20221021,202242,2022,31,313240,2208857,20221020,202242,...,2,2,2,2,2,2,2,2,2,

In [ ]:
display(df_violencia.tail())

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_UNIDADE,DT_OCOR,SEM_PRI,...,CONS_IDO,DELEG_IDOS,DIR_HUMAN,MPU,DELEG_CRIA,DELEG_MULH,DELEG,INFAN_JUV,DEFEN_PUBL,DT_ENCERRA
509145,2,Y09,20221003,202240,2022,42,420540,2691868,20220929,202239,...,2,2,2,2,2,2,2,2,2,
509146,2,Y09,20221003,202240,2022,42,420540,2691868,20220930,202239,...,2,2,2,2,2,2,2,2,2,
509147,2,Y09,20221003,202240,2022,42,420540,3157245,20220905,202236,...,2,2,2,2,9,9,9,9,9,
509148,2,Y09,20221003,202240,2022,43,430240,2252023,20220930,202239,...,2,2,2,2,2,2,2,2,2,
509149,2,Y09,20221003,202240,2022,43,430240,2252023,20220930,202239,...,2,2,2,2,2,2,2,2,2,

In [ ]:
print(df_violencia) #mostra os dados, mas são muitos... então ele corta

       TP_NOT ID_AGRAVO DT_NOTIFIC SEM_NOT NU_ANO SG_UF_NOT ID_MUNICIP  \
0           2      Y09    20221021  202242   2022        35     355710
1           2      Y09    20221021  202242   2022        35     354780
2           2      Y09    20221021  202242   2022        35     355030
3           2      Y09    20221021  202242   2022        35     355030
4           2      Y09    20221021  202242   2022        31     313240
...       ...       ...        ...     ...    ...       ...        ...
509145      2      Y09    20221003  202240   2022        42     420540
509146      2      Y09    20221003  202240   2022        42     420540
509147      2      Y09    20221003  202240   2022        42     420540
509148      2      Y09    20221003  202240   2022        43     430240
509149      2      Y09    20221003  202240   2022        43     430240

       ID_UNIDADE   DT_OCOR SEM_PRI  ... CONS_IDO DELEG_IDOS DIR_HUMAN MPU  \
0         2081377  20221020  202242  ...        2          2         2   2
1         2789590  20221017  202242  ...        2          2         2   2
2         6143121  20221021  202242  ...        2          2         2   2
3         2029596  20221018  202242  ...        2          2         2   2
4         2208857  20221020  202242  ...        2          2         2   2
...           ...       ...     ...  ...      ...        ...       ...  ..
509145    2691868  20220929  202239  ...        2          2         2   2
509146    2691868  20220930  202239  ...        2          2         2   2
509147    3157245  20220905  202236  ...        2          2         2   2
509148    2252023  20220930  202239  ...        2          2         2   2
509149    2252023  20220930  202239  ...        2          2         2   2

       DELEG_CRIA DELEG_MULH DELEG INFAN_JUV DEFEN_PUBL DT_ENCERRA
0               2          2     1         2          2
1               2          2     2         2          2
2               2          2     1         2          2
3               2          2     2         2          2
4               2          2     2         2          2
...           ...        ...   ...       ...        ...        ...
509145          2          2     2         2          2
509146          2          2     2         2          2
509147          9          9     9         9          9
509148          2          2     2         2          2
509149          2          2     2         2          2

[509150 rows x 160 columns]

In [ ]:
column_names = df_violencia.columns.tolist()
print(column_names)
#mostra nomes das colunas

['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP', 'ID_UNIDADE', 'DT_OCOR', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_PAIS', 'NDUPLIC', 'DT_INVEST', 'ID_OCUPA_N', 'SIT_CONJUG', 'DEF_TRANS', 'DEF_FISICA', 'DEF_MENTAL', 'DEF_VISUAL', 'DEF_AUDITI', 'TRAN_MENT', 'TRAN_COMP', 'DEF_OUT', 'DEF_ESPEC', 'SG_UF_OCOR', 'ID_MN_OCOR', 'HORA_OCOR', 'LOCAL_OCOR', 'LOCAL_ESPE', 'OUT_VEZES', 'LES_AUTOP', 'VIOL_FISIC', 'VIOL_PSICO', 'VIOL_TORT', 'VIOL_SEXU', 'VIOL_TRAF', 'VIOL_FINAN', 'VIOL_NEGLI', 'VIOL_INFAN', 'VIOL_LEGAL', 'VIOL_OUTR', 'VIOL_ESPEC', 'AG_FORCA', 'AG_ENFOR', 'AG_OBJETO', 'AG_CORTE', 'AG_QUENTE', 'AG_ENVEN', 'AG_FOGO', 'AG_AMEACA', 'AG_OUTROS', 'AG_ESPEC', 'SEX_ASSEDI', 'SEX_ESTUPR', 'SEX_PUDOR', 'SEX_PORNO', 'SEX_EXPLO', 'SEX_OUTRO', 'SEX_ESPEC', 'PEN_ORAL', 'PEN_ANAL', 'PEN_VAGINA', 'PROC_DST', 'PROC_HIV', 'PROC_HEPB', 'PROC_SANG', 'PROC_SEMEN', 'PROC_VAGIN', 'PROC_CONTR', 'PROC_ABORT', 'CONS_ABORT', 'CONS_GRAV', 'CONS_DST', 'CONS_SUIC', 'CONS_MENT', 'CONS_COMP', 'CONS_ESTRE', 'CONS_OUTR', 'CONS_ESPEC', 'LESAO_NAT', 'LESAO_ESPE', 'LESAO_CORP', 'NUM_ENVOLV', 'REL_SEXUAL', 'REL_PAI', 'REL_MAE', 'REL_PAD', 'REL_CONJ', 'REL_EXCON', 'REL_NAMO', 'REL_EXNAM', 'REL_FILHO', 'REL_DESCO', 'REL_IRMAO', 'REL_CONHEC', 'REL_CUIDA', 'REL_PATRAO', 'REL_INST', 'REL_POL', 'REL_PROPRI', 'REL_OUTROS', 'REL_ESPEC', 'AUTOR_SEXO', 'AUTOR_ALCO', 'ENC_SAUDE', 'ENC_TUTELA', 'ENC_VARA', 'ENC_ABRIGO', 'ENC_SENTIN', 'ENC_DEAM', 'ENC_DPCA', 'ENC_DELEG', 'ENC_MPU', 'ENC_MULHER', 'ENC_CREAS', 'ENC_IML', 'ENC_OUTR', 'ENC_ESPEC', 'REL_TRAB', 'REL_CAT', 'CIRC_LESAO', 'CLASSI_FIN', 'EVOLUCAO', 'DT_OBITO', 'DT_DIGITA', 'DT_TRANSUS', 'DT_TRANSDM', 'DT_TRANSSM', 'DT_TRANSRM', 'DT_TRANSRS', 'DT_TRANSSE', 'REL_MAD', 'TPUNINOT', 'ORIENT_SEX', 'IDENT_GEN', 'VIOL_MOTIV', 'CICL_VID', 'REDE_SAU', 'ASSIST_SOC', 'REDE_EDUCA', 'ATEND_MULH', 'CONS_TUTEL', 'CONS_IDO', 'DELEG_IDOS', 'DIR_HUMAN', 'MPU', 'DELEG_CRIA', 'DELEG_MULH', 'DELEG', 'INFAN_JUV', 'DEFEN_PUBL', 'DT_ENCERRA']

In [ ]:
print("Número de registros:", len(df_violencia))

Número de registros: 509150

In [ ]:
print("Número de variáveis:", len(df_violencia.columns))

Número de variáveis: 160

In [ ]:
print("Valores ausentes por variável:")
print(df_violencia.isnull().sum())

Valores ausentes por variável:
TP_NOT        0
ID_AGRAVO     0
DT_NOTIFIC    0
SEM_NOT       0
NU_ANO        0
             ..
DELEG_MULH    0
DELEG         0
INFAN_JUV     0
DEFEN_PUBL    0
DT_ENCERRA    0
Length: 160, dtype: int64

In [ ]:
for column in df_violencia.columns:
    unique_values = df_violencia[column].unique()
    print("Unique values in column '{}': {}".format(column, unique_values))
#unique_value mostra valor que aparece apenas 1 vez na coluna

Unique values in column 'TP_NOT': ['2']
Unique values in column 'ID_AGRAVO': ['Y09 ']
Unique values in column 'DT_NOTIFIC': ['20221021' '20221022' '20221023' '20221024' '20221025' '20221026'
 '20221027' '20221028' '20221029' '20221030' '20221031' '20221101'
 '20221102' '20221103' '20221104' '20221105' '20221106' '20221107'
 '20221108' '20221109' '20220201' '20220202' '20220203' '20220204'
 '20220205' '20220206' '20220207' '20220208' '20220209' '20220210'
 '20220211' '20220212' '20220213' '20220214' '20220215' '20220216'
 '20220217' '20220218' '20220219' '20220220' '20220221' '20220222'
 '20220223' '20220224' '20220225' '20220826' '20220827' '20220828'
 '20220829' '20220830' '20220831' '20220901' '20220902' '20220903'
 '20220904' '20220905' '20220906' '20220907' '20220908' '20220909'
 '20220910' '20220911' '20220912' '20220913' '20220914' '20221220'
 '20221221' '20221222' '20221223' '20221224' '20221225' '20221226'
 '20221227' '20221228' '20221229' '20221230' '20221231' '20220101'
 '20220102' '20220103' '20220104' '20220105' '20220106' '20220107'
 '20220108' '20220109' '20220110' '20220111' '20220112' '20220113'
 '20220114' '20220115' '20220116' '20220117' '20220118' '20220119'
 '20221009' '20220120' '20220121' '20220122' '20220123' '20220124'
 '20220125' '20220126' '20220127' '20220128' '20220129' '20220130'
 '20220131' '20220226' '20220227' '20220228' '20220301' '20220302'
 '20220303' '20220304' '20220305' '20220621' '20220306' '20220307'
 '20220308' '20220309' '20220310' '20220311' '20220312' '20220313'
 '20220314' '20220315' '20220316' '20220317' '20220318' '20220319'
 '20220320' '20220321' '20220322' '20220323' '20220324' '20220325'
 '20220326' '20220327' '20220328' '20220329' '20220330' '20220331'
 '20220401' '20220402' '20220403' '20220404' '20220405' '20220406'
 '20220407' '20220408' '20220409' '20220410' '20220411' '20220412'
 '20220413' '20220414' '20220415' '20220416' '20220417' '20220418'
 '20220419' '20220420' '20220421' '20220422' '20220423' '20220424'
 '20220425' '20220426' '20220427' '20220428' '20220429' '20220430'
 '20220501' '20220502' '20220503' '20220504' '20220505' '20220506'
 '20220507' '20220508' '20220509' '20220510' '20220511' '20220512'
 '20220513' '20220514' '20220515' '20220516' '20220517' '20220518'
 '20220519' '20220520' '20220521' '20220522' '20220523' '20220524'
 '20220525' '20220526' '20220527' '20220528' '20220529' '20220530'
 '20220531' '20220601' '20220602' '20220603' '20220604' '20220605'
 '20220606' '20220607' '20220608' '20220609' '20220610' '20220611'
 '20220612' '20220613' '20220614' '20220615' '20220616' '20220617'
 '20220618' '20220619' '20220620' '20220622' '20220623' '20220624'
 '20220625' '20220626' '20220627' '20220628' '20220629' '20220630'
 '20220701' '20220702' '20220703' '20220704' '20220707' '20220705'
 '20220706' '20220708' '20220709' '20220710' '20220711' '20220712'
 '20220713' '20220714' '20220715' '20220716' '20220717' '20220718'
 '20220719' '20220720' '20220721' '20220722' '20220723' '20220724'
 '20220725' '20220726' '20220727' '20220728' '20220729' '20220730'
 '20220731' '20220801' '20220802' '20220808' '20220803' '20220804'
 '20220805' '20220806' '20220807' '20220809' '20220810' '20220811'
 '20220812' '20220813' '20220814' '20220815' '20220816' '20220817'
 '20220818' '20220819' '20220820' '20220821' '20220822' '20220823'
 '20220824' '20220825' '20220915' '20220916' '20220917' '20220918'
 '20220919' '20220920' '20220921' '20220922' '20220923' '20220924'
 '20220925' '20220926' '20220927' '20220928' '20220929' '20220930'
 '20221001' '20221002' '20221003' '20221004' '20221005' '20221006'
 '20221007' '20221008' '20221010' '20221011' '20221012' '20221013'
 '20221014' '20221015' '20221016' '20221017' '20221018' '20221019'
 '20221020' '20221110' '20221111' '20221112' '20221113' '20221114'
 '20221115' '20221116' '20221117' '20221118' '20221119' '20221120'
 '20221121' '20221122' '20221123' '20221124' '20221125' '20221126'
 '20221127' '20221128' '20221129' '20221130' '20221201' '20221202'
 '20221203' '20221204' '20221205' '20221206' '20221207' '20221208'
 '20221209' '20221210' '20221211' '20221212' '20221213' '20221214'
 '20221215' '20221216' '20221217' '20221218' '20221219']
Unique values in column 'SEM_NOT': ['202242' '202243' '202244' '202245' '202205' '202206' '202207' '202208'
 '202234' '202235' '202236' '202237' '202251' '202252' '202152' '202201'
 '202202' '202203' '202241' '202204' '202209' '202225' '202210' '202211'
 '202212' '202213' '202214' '202215' '202216' '202217' '202218' '202219'
 '202220' '202221' '202222' '202223' '202224' '202226' '202227' '202228'
 '202229' '202230' '202231' '202232' '202233' '202238' '202239' '202240'
 '202246' '202247' '202248' '202249' '202250' '02152 ']
Unique values in column 'NU_ANO': ['2022']
Unique values in column 'SG_UF_NOT': ['35' '31' '43' '23' '52' '41' '13' '26' '42' '22' '28' '15' '25' '24'
 '17' '29' '27' '21' '14' '53' '50' '11' '16' '33' '12' '51' '32' 'CO']
Unique values in column 'ID_MUNICIP': ['355710' '354780' '355030' ... '351900' '210780' '520250']
Unique values in column 'ID_UNIDADE': ['2081377' '2789590' '6143121' ... '0038016' '5635241' '2535963']
Unique values in column 'DT_OCOR': ['20221020' '20221017' '20221021' ... '20130703' '19800309' '19780113']
Unique values in column 'SEM_PRI': ['202242' '202240' '202241' ... '196143' '198011' '197802']
Unique values in column 'ANO_NASC': ['1992' '1979' '1985' '2006' '1995' '2008' '1975' '1982' '2003' '1986'
 '1947' '1997' '2007' '2001' '1974' '2002' '1957' '1991' '2005' '2021'
 '1972' '2009' '1994' '1988' '1984' '1978' '1989' '1963' '1962' '1998'
 '1964' '1973' '1943' '1966' '1954' '1983' '2015' '2000' '1999' '2018'
 '1980' '1990' '2011' '    ' '1965' '1993' '1971' '1996' '1969' '2022'
 '1970' '1952' '2017' '1967' '2012' '1987' '2010' '1955' '2013' '1959'
 '1944' '2014' '1981' '2020' '1976' '1977' '1946' '2016' '2004' '1941'
 '1968' '1950' '1961' '1948' '1958' '1938' '1956' '2019' '1951' '1960'
 '1940' '1953' '1949' '1931' '1942' '1932' '1945' '1934' '1936' '1923'
 '1939' '1935' '1933' '1929' '1927' '1937' '1925' '1930' '1900' '1928'
 '1920' '1926' '1922' '1917' '1921' '1924' '1918' '1919' '1908' '1916'
 '1915' '1907' '1910' '0984' '1901' '1905' '1914' '2099' '1912']
Unique values in column 'NU_IDADE_N': ['4030' '4042' '4037' '4016' '4026' '4014' '4043' '4047' '4040' '4019'
 '4036' '4075' '4024' '4015' '4021' '4048' '4020' '4065' '4031' '4017'
 '4001' '4050' '4013' '4027' '4034' '4038' '4044' '4033' '4059' '4057'
 '4028' '4079' '4046' '4025' '4029' '4056' '4068' '4039' '4006' '4032'
 '4022' '4004' '4011' '4023' '4060' '4051' '4053' '3008' '4007' '4052'
 '4070' '2023' '4054' '4010' '4012' '4018' '4064' '4067' '4035' '4009'
 '4008' '3011' '4005' '3006' '4063' '4078' '4041' '4045' '4076' '4003'
 '4081' '4072' '4061' '4073' '4055' '4058' '4002' '4084' '2013' '2000'
 '4049' '4062' '4066' '2009' '3010' '4069' '4074' '3002' '4071' '3007'
 '3009' '4077' '4091' '3005' '2024' '4080' '3003' '4089' '4088' '2005'
 '4082' '4086' '4098' '2020' '3001' '2019' '3004' '1015' '2003' '2018'
 '2001' '4094' '2022' '4087' '2002' '2015' '4083' '4093' '2014' '4085'
 '4095' '2006' '4090' '4099' '2028' '2025' '4097' '2026' '2016' '4092'
 '4000' '4102' '2027' '2029' '4096' '2012' '2021' '2004' '2007' '2030'
 '2011' '2017' '4105' '4101' '4100' '2008' '4104' '2010' '4113' '1001'
 '4107' '4114' '4112' '1005' '4103' '4106' '4122' '4121' '4120' '4116'
 '4108' '4110' '1022']
Unique values in column 'CS_SEXO': ['M' 'F' 'I']
Unique values in column 'CS_GESTANT': ['6' '5' '9' '2' '3' '1' '4' ' ']
Unique values in column 'CS_RACA': ['1' '4' '2' '9' ' ' '5' '3']
Unique values in column 'CS_ESCOL_N': ['06' '08' '05' '09' '03' '  ' '01' '10' '02' '04' '07' '00']
Unique values in column 'SG_UF': ['35' '31' '43' '23' '52' '41' '13' '26' '42' '22' '28' '15' '25' '24'
 '17' '29' '27' '21' '14' '53' '50' '11' '16' '33' '12' '51' '  ' '32']
Unique values in column 'ID_MN_RESI': ['354980' '354780' '355030' ... '421775' '420253' '220198']
Unique values in column 'ID_PAIS': ['1   ' '19  ' '199 ' '126 ' '32  ' '    ' '46  ' '7   ' '138 ' '44  '
 '68  ' '45  ']
Unique values in column 'NDUPLIC': [' ']
Unique values in column 'DT_INVEST': ['        ']
Unique values in column 'ID_OCUPA_N': ['XXX   ' '      ' '231205' ... '914110' '214515' '823330']
Unique values in column 'SIT_CONJUG': ['1' '2' '9' ' ' '8' '4' '3']
Unique values in column 'DEF_TRANS': ['2' '9' '1' ' ' '8']
Unique values in column 'DEF_FISICA': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'DEF_MENTAL': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'DEF_VISUAL': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'DEF_AUDITI': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'TRAN_MENT': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'TRAN_COMP': ['8' '1' ' ' '2' '9' '3']
Unique values in column 'DEF_OUT': ['8' '2' ' ' '1' '9' '3']
Unique values in column 'DEF_ESPEC': ['                              ' 'DEPRESSAO                     '
 'TRANST BIPOLAR                ' ... 'TRANSTORNOS AFETIVOS BIPOLARES'
 'DEPRESSAO/BODERLINE           ' 'ESQUIZOFRENIA EX USUARIA COCAI']
Unique values in column 'SG_UF_OCOR': ['35' '31' '43' '  ' '23' '52' '41' '13' '26' '42' '28' '15' '25' '24'
 '17' '29' '22' '21' '14' '53' '27' '50' '11' '16' '33' '12' '51' '32'
 '/N']
Unique values in column 'ID_MN_OCOR': ['355710' '350000' '355030' ... '421569' '221170' '355520']
Unique values in column 'HORA_OCOR': ['20:00' '     ' '00:00' ... '00000' '05:51' '05:47']
Unique values in column 'LOCAL_OCOR': ['01' '99' '06' '  ' '09' '02' '05' '07' '03' '04' '08']
Unique values in column 'LOCAL_ESPE': ['                              ' 'CAPS                          '
 'CAP                           ' ... 'LOCAL DO SERVICO              '
 'TRBALAHO                      ' 'TRABALHO FAZENDA              ']
Unique values in column 'OUT_VEZES': ['2' '1' '9' ' ' '0']
Unique values in column 'LES_AUTOP': ['1' '2' ' ' '9']
Unique values in column 'VIOL_FISIC': ['2' '1' ' ' '9']
Unique values in column 'VIOL_PSICO': ['2' ' ' '1' '9']
Unique values in column 'VIOL_TORT': ['2' ' ' '1' '9']
Unique values in column 'VIOL_SEXU': ['2' '1' ' ' '9']
Unique values in column 'VIOL_TRAF': ['2' ' ' '9' '1']
Unique values in column 'VIOL_FINAN': ['2' ' ' '1' '9']
Unique values in column 'VIOL_NEGLI': ['2' ' ' '1' '9']
Unique values in column 'VIOL_INFAN': ['2' ' ' '9' '1']
Unique values in column 'VIOL_LEGAL': ['2' ' ' '9' '1']
Unique values in column 'VIOL_OUTR': ['1' '2' ' ' '9']
Unique values in column 'VIOL_ESPEC': ['777                           ' '                              '
 'TENTATIVA DE SUICIDIO         ' ... 'EM FUNCAO DA SUA CONDUTA      '
 'USO DE CIGARRO                ' 'DOPAGEM                       ']
Unique values in column 'AG_FORCA': ['2' '1' ' ' '9']
Unique values in column 'AG_ENFOR': ['2' '1' ' ' '9']
Unique values in column 'AG_OBJETO': ['2' '1' ' ' '9']
Unique values in column 'AG_CORTE': ['2' ' ' '9' '1']
Unique values in column 'AG_QUENTE': ['2' ' ' '9' '1']
Unique values in column 'AG_ENVEN': ['1' '2' ' ' '9']
Unique values in column 'AG_FOGO': ['2' ' ' '9' '1']
Unique values in column 'AG_AMEACA': ['2' ' ' '9' '1']
Unique values in column 'AG_OUTROS': ['2' '1' ' ' '9']
Unique values in column 'AG_ESPEC': ['                              ' 'INGESTAO DE MEDICAMENTOS      '
 'SEXUAL                        ' ... 'XINGAMEN                      '
 'NEGLIGENCIA EM CUIDADOS BASICO' 'ARREMESSOU BALDE              ']
Unique values in column 'SEX_ASSEDI': ['8' '9' ' ' '2' '1']
Unique values in column 'SEX_ESTUPR': ['8' '9' ' ' '1' '2']
Unique values in column 'SEX_PUDOR': [' ' '8']
Unique values in column 'SEX_PORNO': ['8' '9' ' ' '2' '1']
Unique values in column 'SEX_EXPLO': ['8' '9' ' ' '2' '1']
Unique values in column 'SEX_OUTRO': ['8' '9' ' ' '2' '1']
Unique values in column 'SEX_ESPEC': ['                              ' 'ABUSOS                        '
 'SUSPEITA ABUSO                ' ... 'ABUSOS SEM OCORRENC DE PENETRC'
 'EXPOSICAO CENAS DE SEXO       ' '*****                         ']
Unique values in column 'PEN_ORAL': [' ']
Unique values in column 'PEN_ANAL': [' ']
Unique values in column 'PEN_VAGINA': [' ']
Unique values in column 'PROC_DST': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_HIV': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_HEPB': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_SANG': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_SEMEN': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_VAGIN': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_CONTR': ['8' '9' ' ' '2' '1']
Unique values in column 'PROC_ABORT': ['8' '9' ' ' '2' '1']
Unique values in column 'CONS_ABORT': [' ']
Unique values in column 'CONS_GRAV': [' ']
Unique values in column 'CONS_DST': [' ']
Unique values in column 'CONS_SUIC': [' ']
Unique values in column 'CONS_MENT': [' ']
Unique values in column 'CONS_COMP': [' ']
Unique values in column 'CONS_ESTRE': [' ']
Unique values in column 'CONS_OUTR': [' ']
Unique values in column 'CONS_ESPEC': ['                              ']
Unique values in column 'LESAO_NAT': ['  ']
Unique values in column 'LESAO_ESPE': ['                              ']
Unique values in column 'LESAO_CORP': ['  ']
Unique values in column 'NUM_ENVOLV': ['1' ' ' '2' '9']
Unique values in column 'REL_SEXUAL': [' ' '8']
Unique values in column 'REL_PAI': ['2' ' ' '9' '1']
Unique values in column 'REL_MAE': ['2' ' ' '1' '9']
Unique values in column 'REL_PAD': ['2' ' ' '9' '1']
Unique values in column 'REL_CONJ': ['2' '1' ' ' '9']
Unique values in column 'REL_EXCON': ['2' ' ' '9' '1']
Unique values in column 'REL_NAMO': ['2' '1' ' ' '9']
Unique values in column 'REL_EXNAM': ['2' ' ' '1' '9']
Unique values in column 'REL_FILHO': ['2' ' ' '9' '1']
Unique values in column 'REL_DESCO': ['2' ' ' '9' '1']
Unique values in column 'REL_IRMAO': ['2' ' ' '9' '1']
Unique values in column 'REL_CONHEC': ['2' ' ' '9' '1']
Unique values in column 'REL_CUIDA': ['2' ' ' '9' '1']
Unique values in column 'REL_PATRAO': ['2' ' ' '9' '1']
Unique values in column 'REL_INST': ['2' ' ' '9' '1']
Unique values in column 'REL_POL': ['2' ' ' '9' '1']
Unique values in column 'REL_PROPRI': ['1' '2' ' ' '9']
Unique values in column 'REL_OUTROS': ['2' '1' ' ' '9']
Unique values in column 'REL_ESPEC': ['                              ' 'TIA                           '
 'ENTEADO                       ' ... 'MAE DA CUNHADA                '
 'COMP DO EX MARIDO             ' 'SOBRINHO E FILHOS             ']
Unique values in column 'AUTOR_SEXO': ['1' '2' ' ' '3' '9']
Unique values in column 'AUTOR_ALCO': ['1' '9' '2' ' ']
Unique values in column 'ENC_SAUDE': [' ' '1' '2' '9']
Unique values in column 'ENC_TUTELA': [' ' '2' '1' '9']
Unique values in column 'ENC_VARA': [' ' '2' '1' '9']
Unique values in column 'ENC_ABRIGO': [' ' '/']
Unique values in column 'ENC_SENTIN': [' ' '/']
Unique values in column 'ENC_DEAM': [' ' '2' '1' '9']
Unique values in column 'ENC_DPCA': [' ' '2' '1' '9']
Unique values in column 'ENC_DELEG': [' ' '2' '1' '9']
Unique values in column 'ENC_MPU': [' ' '2' '1' '9']
Unique values in column 'ENC_MULHER': [' ' '2' '1' '9']
Unique values in column 'ENC_CREAS': [' ' '2' '1' '9']
Unique values in column 'ENC_IML': [' ' '/']
Unique values in column 'ENC_OUTR': [' ' '/']
Unique values in column 'ENC_ESPEC': ['                              ' '/N                            ']
Unique values in column 'REL_TRAB': ['2' ' ' '9' '1']
Unique values in column 'REL_CAT': ['8' ' ' '1' '9' '2']
Unique values in column 'CIRC_LESAO': ['X61.0' 'X61  ' '     ' ... 'X90.4' 'K29.9' 'T20.1']
Unique values in column 'CLASSI_FIN': [' ']
Unique values in column 'EVOLUCAO': [' ']
Unique values in column 'DT_OBITO': ['        ']
Unique values in column 'DT_DIGITA': ['        ']
Unique values in column 'DT_TRANSUS': ['        ']
Unique values in column 'DT_TRANSDM': ['        ']
Unique values in column 'DT_TRANSSM': ['        ']
Unique values in column 'DT_TRANSRM': ['        ']
Unique values in column 'DT_TRANSRS': ['        ']
Unique values in column 'DT_TRANSSE': ['        ']
Unique values in column 'REL_MAD': ['2' ' ' '9' '1']
Unique values in column 'TPUNINOT': ['  ']
Unique values in column 'ORIENT_SEX': ['1' '9' ' ' '8' '3' '2']
Unique values in column 'IDENT_GEN': ['8' '9' ' ' '2' '1' '3']
Unique values in column 'VIOL_MOTIV': ['88' '99' '09' '06' '  ' '01' '08' '02' '07' '04' '05' '03']
Unique values in column 'CICL_VID': ['4' '2' '3' '9' ' ' '5' '1']
Unique values in column 'REDE_SAU': ['1' '2' ' ' '9']
Unique values in column 'ASSIST_SOC': ['2' '1' ' ' '9']
Unique values in column 'REDE_EDUCA': ['2' ' ' '9' '1']
Unique values in column 'ATEND_MULH': ['2' '1' ' ' '9']
Unique values in column 'CONS_TUTEL': ['2' '1' ' ' '9']
Unique values in column 'CONS_IDO': ['2' ' ' '9' '1']
Unique values in column 'DELEG_IDOS': ['2' ' ' '9' '1']
Unique values in column 'DIR_HUMAN': ['2' ' ' '9' '1']
Unique values in column 'MPU': ['2' ' ' '9' '1']
Unique values in column 'DELEG_CRIA': ['2' ' ' '9' '1']
Unique values in column 'DELEG_MULH': ['2' '1' ' ' '9']
Unique values in column 'DELEG': ['1' '2' ' ' '9']
Unique values in column 'INFAN_JUV': ['2' ' ' '9' '1']
Unique values in column 'DEFEN_PUBL': ['2' ' ' '9' '1']
Unique values in column 'DT_ENCERRA': ['        ']

In [ ]:
for column in df_violencia.columns:
    try:
        pd.to_numeric(df_violencia[column])
        print("Column '{}' data type: Integer or Float".format(column))
    except ValueError:
        print("Column '{}' data type: Text or Varchar".format(column))

Column 'TP_NOT' data type: Integer or Float
Column 'ID_AGRAVO' data type: Text or Varchar
Column 'DT_NOTIFIC' data type: Integer or Float
Column 'SEM_NOT' data type: Integer or Float
Column 'NU_ANO' data type: Integer or Float
Column 'SG_UF_NOT' data type: Text or Varchar
Column 'ID_MUNICIP' data type: Text or Varchar
Column 'ID_UNIDADE' data type: Text or Varchar
Column 'DT_OCOR' data type: Text or Varchar
Column 'SEM_PRI' data type: Integer or Float
Column 'ANO_NASC' data type: Text or Varchar
Column 'NU_IDADE_N' data type: Integer or Float
Column 'CS_SEXO' data type: Text or Varchar
Column 'CS_GESTANT' data type: Text or Varchar
Column 'CS_RACA' data type: Text or Varchar
Column 'CS_ESCOL_N' data type: Text or Varchar
Column 'SG_UF' data type: Text or Varchar
Column 'ID_MN_RESI' data type: Text or Varchar
Column 'ID_PAIS' data type: Text or Varchar
Column 'NDUPLIC' data type: Text or Varchar
Column 'DT_INVEST' data type: Text or Varchar
Column 'ID_OCUPA_N' data type: Text or Varchar
Column 'SIT_CONJUG' data type: Text or Varchar
Column 'DEF_TRANS' data type: Text or Varchar
Column 'DEF_FISICA' data type: Text or Varchar
Column 'DEF_MENTAL' data type: Text or Varchar
Column 'DEF_VISUAL' data type: Text or Varchar
Column 'DEF_AUDITI' data type: Text or Varchar
Column 'TRAN_MENT' data type: Text or Varchar
Column 'TRAN_COMP' data type: Text or Varchar
Column 'DEF_OUT' data type: Text or Varchar
Column 'DEF_ESPEC' data type: Text or Varchar
Column 'SG_UF_OCOR' data type: Text or Varchar
Column 'ID_MN_OCOR' data type: Text or Varchar
Column 'HORA_OCOR' data type: Text or Varchar
Column 'LOCAL_OCOR' data type: Text or Varchar
Column 'LOCAL_ESPE' data type: Text or Varchar
Column 'OUT_VEZES' data type: Text or Varchar
Column 'LES_AUTOP' data type: Text or Varchar
Column 'VIOL_FISIC' data type: Text or Varchar
Column 'VIOL_PSICO' data type: Text or Varchar
Column 'VIOL_TORT' data type: Text or Varchar
Column 'VIOL_SEXU' data type: Text or Varchar
Column 'VIOL_TRAF' data type: Text or Varchar
Column 'VIOL_FINAN' data type: Text or Varchar
Column 'VIOL_NEGLI' data type: Text or Varchar
Column 'VIOL_INFAN' data type: Text or Varchar
Column 'VIOL_LEGAL' data type: Text or Varchar
Column 'VIOL_OUTR' data type: Text or Varchar
Column 'VIOL_ESPEC' data type: Text or Varchar
Column 'AG_FORCA' data type: Text or Varchar
Column 'AG_ENFOR' data type: Text or Varchar
Column 'AG_OBJETO' data type: Text or Varchar
Column 'AG_CORTE' data type: Text or Varchar
Column 'AG_QUENTE' data type: Text or Varchar
Column 'AG_ENVEN' data type: Text or Varchar
Column 'AG_FOGO' data type: Text or Varchar
Column 'AG_AMEACA' data type: Text or Varchar
Column 'AG_OUTROS' data type: Text or Varchar
Column 'AG_ESPEC' data type: Text or Varchar
Column 'SEX_ASSEDI' data type: Text or Varchar
Column 'SEX_ESTUPR' data type: Text or Varchar
Column 'SEX_PUDOR' data type: Text or Varchar
Column 'SEX_PORNO' data type: Text or Varchar
Column 'SEX_EXPLO' data type: Text or Varchar
Column 'SEX_OUTRO' data type: Text or Varchar
Column 'SEX_ESPEC' data type: Text or Varchar
Column 'PEN_ORAL' data type: Text or Varchar
Column 'PEN_ANAL' data type: Text or Varchar
Column 'PEN_VAGINA' data type: Text or Varchar
Column 'PROC_DST' data type: Text or Varchar
Column 'PROC_HIV' data type: Text or Varchar
Column 'PROC_HEPB' data type: Text or Varchar
Column 'PROC_SANG' data type: Text or Varchar
Column 'PROC_SEMEN' data type: Text or Varchar
Column 'PROC_VAGIN' data type: Text or Varchar
Column 'PROC_CONTR' data type: Text or Varchar
Column 'PROC_ABORT' data type: Text or Varchar
Column 'CONS_ABORT' data type: Text or Varchar
Column 'CONS_GRAV' data type: Text or Varchar
Column 'CONS_DST' data type: Text or Varchar
Column 'CONS_SUIC' data type: Text or Varchar
Column 'CONS_MENT' data type: Text or Varchar
Column 'CONS_COMP' data type: Text or Varchar
Column 'CONS_ESTRE' data type: Text or Varchar
Column 'CONS_OUTR' data type: Text or Varchar
Column 'CONS_ESPEC' data type: Text or Varchar
Column 'LESAO_NAT' data type: Text or Varchar
Column 'LESAO_ESPE' data type: Text or Varchar
Column 'LESAO_CORP' data type: Text or Varchar
Column 'NUM_ENVOLV' data type: Text or Varchar
Column 'REL_SEXUAL' data type: Text or Varchar
Column 'REL_PAI' data type: Text or Varchar
Column 'REL_MAE' data type: Text or Varchar
Column 'REL_PAD' data type: Text or Varchar
Column 'REL_CONJ' data type: Text or Varchar
Column 'REL_EXCON' data type: Text or Varchar
Column 'REL_NAMO' data type: Text or Varchar
Column 'REL_EXNAM' data type: Text or Varchar
Column 'REL_FILHO' data type: Text or Varchar
Column 'REL_DESCO' data type: Text or Varchar
Column 'REL_IRMAO' data type: Text or Varchar
Column 'REL_CONHEC' data type: Text or Varchar
Column 'REL_CUIDA' data type: Text or Varchar
Column 'REL_PATRAO' data type: Text or Varchar
Column 'REL_INST' data type: Text or Varchar
Column 'REL_POL' data type: Text or Varchar
Column 'REL_PROPRI' data type: Text or Varchar
Column 'REL_OUTROS' data type: Text or Varchar
Column 'REL_ESPEC' data type: Text or Varchar
Column 'AUTOR_SEXO' data type: Text or Varchar
Column 'AUTOR_ALCO' data type: Text or Varchar
Column 'ENC_SAUDE' data type: Text or Varchar
Column 'ENC_TUTELA' data type: Text or Varchar
Column 'ENC_VARA' data type: Text or Varchar
Column 'ENC_ABRIGO' data type: Text or Varchar
Column 'ENC_SENTIN' data type: Text or Varchar
Column 'ENC_DEAM' data type: Text or Varchar
Column 'ENC_DPCA' data type: Text or Varchar
Column 'ENC_DELEG' data type: Text or Varchar
Column 'ENC_MPU' data type: Text or Varchar
Column 'ENC_MULHER' data type: Text or Varchar
Column 'ENC_CREAS' data type: Text or Varchar
Column 'ENC_IML' data type: Text or Varchar
Column 'ENC_OUTR' data type: Text or Varchar
Column 'ENC_ESPEC' data type: Text or Varchar
Column 'REL_TRAB' data type: Text or Varchar
Column 'REL_CAT' data type: Text or Varchar
Column 'CIRC_LESAO' data type: Text or Varchar
Column 'CLASSI_FIN' data type: Text or Varchar
Column 'EVOLUCAO' data type: Text or Varchar
Column 'DT_OBITO' data type: Text or Varchar
Column 'DT_DIGITA' data type: Text or Varchar
Column 'DT_TRANSUS' data type: Text or Varchar
Column 'DT_TRANSDM' data type: Text or Varchar
Column 'DT_TRANSSM' data type: Text or Varchar
Column 'DT_TRANSRM' data type: Text or Varchar
Column 'DT_TRANSRS' data type: Text or Varchar
Column 'DT_TRANSSE' data type: Text or Varchar
Column 'REL_MAD' data type: Text or Varchar
Column 'TPUNINOT' data type: Text or Varchar
Column 'ORIENT_SEX' data type: Text or Varchar
Column 'IDENT_GEN' data type: Text or Varchar
Column 'VIOL_MOTIV' data type: Text or Varchar
Column 'CICL_VID' data type: Text or Varchar
Column 'REDE_SAU' data type: Text or Varchar
Column 'ASSIST_SOC' data type: Text or Varchar
Column 'REDE_EDUCA' data type: Text or Varchar
Column 'ATEND_MULH' data type: Text or Varchar
Column 'CONS_TUTEL' data type: Text or Varchar
Column 'CONS_IDO' data type: Text or Varchar
Column 'DELEG_IDOS' data type: Text or Varchar
Column 'DIR_HUMAN' data type: Text or Varchar
Column 'MPU' data type: Text or Varchar
Column 'DELEG_CRIA' data type: Text or Varchar
Column 'DELEG_MULH' data type: Text or Varchar
Column 'DELEG' data type: Text or Varchar
Column 'INFAN_JUV' data type: Text or Varchar
Column 'DEFEN_PUBL' data type: Text or Varchar
Column 'DT_ENCERRA' data type: Text or Varchar

In [43]:
cs_sexo_column = df_violencia['CS_SEXO']

In [47]:
df_violencia['CS_SEXO'] = df_violencia['CS_SEXO'].str.strip().str.lower() #strip limpa espaços em branco, lower deixa tudo em lowercase para não haver diferença entre 'M' e 'm'

count_m = (df_violencia['CS_SEXO'] == 'm').sum() #'==' cria uma operação boleana e dps o sum soma a quantidade de true que existe para o valor m
count_f = (df_violencia['CS_SEXO'] == 'f').sum()
count_i = (df_violencia['CS_SEXO'] == 'i').sum()

print("Count of 'm':", count_m)
print("Count of 'f':", count_f)
print("Count of 'i':", count_i)

Count of 'm': 150890
Count of 'f': 358069
Count of 'i': 191